version: '2'

services:
  db:
    build: ./db
    restart: always
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    #ports:
      #- 3306:3306
    volumes:
      - ./db/var/lib/mysql/:/var/lib/mysql
      - ./db/etc/mysql/conf.d/:/etc/mysql/conf.d/
    depends_on:
      - memcached
    container_name: db
  phpmyadmin:
    image:
      phpmyadmin/phpmyadmin
    #ports:
      #- 8080:80
    env_file:
      - ".env"
    container_name: phpmyadmin
    depends_on:
      - db
  djangoblog:
    build: ./djangoblog/
    restart: always
    env_file:
      - ".env"
    command:  bash -c  'sh DjangoBlog/bin/docker_start.sh'
    volumes:
      - ./djangoblog/codes:/code
    #ports:
      #- "8000:8000"
    links:
      - db
    depends_on:
      - db
    container_name: djangoblog
  wordpress:
    build: ./wordpress
    restart: always
    #ports:
      #- "9000:9000"
    env_file:
      - ".env"
    volumes:
      - ./wordpress/wordpress:/wordpress
      - ./wordpress/php/usr/local/etc/:/usr/local/etc/
    links:
      - db
    depends_on:
      - db
    container_name: wordpress
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/lylinux.net /etc/letsencrypt/live/lylinux.net/
      - ./nginx/nginx/ /etc/nginx
      - ./nginx/resource /resource/
    volumes_from:
      - djangoblog
      - wordpress
    links:
      - djangoblog:djangoblog
      - wordpress:wordpress
      - phpmyadmin:phpmyadmin
    container_name: nginx
  memcached:
    build: ./memcached/
    container_name: memcached
